# NumPy

## Used to store Multi-dimensional Arrays
## Why use this over lists?
### Main difference is speed
#### NumPy uses fixed types. So a 5 stored in it will be cast into a 32-bit type (4 bytes). You can specify int16 or int8.
#### In lists, there are more resources stored: size, reference count, object value, and type. That uses a lot of memory and slows down the whole system.
### NumPy also uses contiguous memory, instead of pointers for each cell as in lists, making it slow.
### In NumPy, we can do basic operations like insertions, deletions, and much more. Like using math operators like *, directly with arrays.
### Matlab replacement (maybe), SciPy is even more powerful.
### Backend for Matplotlib, Pandas, etc.


In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype = "int16") # Try to specify the type for more efficiency
print(a)

[1 2 3]


In [3]:
b = np.array([[1, 0.1, 2], [0.1, 0.3, 0.6]])
print(b)

[[1.  0.1 2. ]
 [0.1 0.3 0.6]]


In [4]:
# Get dimensions
print(a.ndim)
print(b.ndim)
#Get shape
print(a.shape)
print(b.shape)

1
2
(3,)
(2, 3)


In [5]:
# Get type
print(a.dtype)
print(a.itemsize)
print(a.size) # Total number of elements
print(a.size * a.itemsize) # Total size
print(a.nbytes) # Total size

int16
2
3
6
6


In [6]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [7]:
print(a[1,2])
a[1,2] = 20
print(a[1,2])
print(a[1,:]) # Get row
a[1,:] = [5,5,5,5,5,5,5] # Can also be written as a[1, :] = 5
print(a[1, :])
print(a[0,1])
print(a[:, 3]) # Get column

# [startindex, endindex, stepsize]
print(a[0, 1: 6: 2])

10
20
[ 8  9 20 11 12 13 14]
[5 5 5 5 5 5 5]
2
[4 5]
[2 4 6]


In [8]:
# 3D array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

# Tip to access elements - go outside in
print(b[0, 1, 1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


In [9]:
z = np.zeros(5)
print(z)
z = np.zeros((2,3,3), dtype = "int16")
print(z)

o = np.ones((4,2))
print(o)

x = np.full((2,2,3), 99) # List full of any element x [the first parameter is a shape]
print(x)

[0. 0. 0. 0. 0.]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]]]


In [10]:
# Random decimal numbers
np.random.rand(4, 2) # Shape

array([[0.22251345, 0.44545853],
       [0.71069729, 0.57981115],
       [0.79223436, 0.56848365],
       [0.70423916, 0.86177095]])

In [11]:
# Random interger numbers
print(np.random.randint(7, size=(3, 3))) # First parameter is the end_value - 1
print(np.random.randint(4, 7, size=(3, 3))) # Start and end - 1

[[3 0 3]
 [4 5 5]
 [4 6 2]]
[[6 5 4]
 [5 5 5]
 [5 4 4]]


In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr = np.array([[1, 2, 3]])
arr1 = np.repeat(arr, 3, axis = 0)
print(arr)
print(arr1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
example = np.zeros((5, 5), dtype = "int8")
example[0, :] = np.ones(1, dtype = "int8")
example[-1, :] = np.ones(1)
example[:, 0] = np.ones(1)
example[:, -1] = np.ones(1)
example[2, 2] = 9
example

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [15]:
 # Better way to do the example
example = np.ones((5, 5), dtype = "int8")
x = np.zeros((3, 3), dtype = "int8")
x[1, 1] = 9
example[1:4, 1:4] = x
example

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

## Be careful when copying arrays
### They are passed by reference

In [16]:
a = np.array([1, 2, 3, 4])
a += 2
print(a)
# Similarly all other arithmetic operators
# Can also be done with matrices, given they are compatible wrt shape and other properties, if applicable
a = np.sin(a)
print(a)

[3 4 5 6]
[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [17]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(np.matmul(a, b))

[[6. 6.]
 [6. 6.]]


In [18]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [19]:
a = np.array([[1, 3, 2], [4, 5, 6]])
print(np.max(a))
print(np.min(a))
print(np.max(a[0, :])) # First row
print(np.max(a, axis=1)) # Row wise max
print(np.sum(a))
print(np.sum(a, axis=0)) # Column wise sum

6
1
3
[3 6]
21
[5 8 8]


In [20]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a = a.reshape((5, 2))
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [21]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
x = np.vstack([v1, v2, v1, v2]) # hstack is used for horizontal stack
print(x)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [23]:
# Boolean Masking
a = np.ones((5, 6))
print(a > 1)
print((a > 1) & (a < 100))
print(a[a > 1]) # Grab elements with conditions
# This is done because you can index in NumPy with a list
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,6]])
# Can be used with np.all and np.any -- combining with axis gives more functionality

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
[]
[2 3 7]


In [38]:
example = np.arange(1, 31, 1)
example = example.reshape((6, 5))
print(example)
print(example[2:4, :2])
print(example[[0, 1, 2, 3], [1, 2, 3, 4]])
print(example[[0, 4, 5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
